import type {
  Classification,
  DiagnosisReport,
  DraftQuestion,
  Explanation,
  PlanNarrative,
} from "./validators";
import type {
  ClassifyInput,
  DiagnoseInput,
  ExplanationInput,
  PlanInput,
  QuestionGenInput,
} from "./types";

export class MockProvider {
  async generateExplanation(_input?: ExplanationInput): Promise<Explanation> {
    return {
      correct_explanation:
        "This is a mock explanation used for local testing. Replace with NVIDIA output later.",
      distractor_explanations: {
        A: "Mock distractor explanation for A.",
        B: "Mock distractor explanation for B.",
        C: "Mock distractor explanation for C.",
        D: "Mock distractor explanation for D.",
      },
      key_concept: "Mock key concept",
      common_misconception: "Mock misconception",
    };
  }

  async generateQuestion(input?: QuestionGenInput): Promise<DraftQuestion[]> {
    const count = Math.max(1, input?.count ?? 1);

    return Array.from({ length: count }, (_, index) => ({
      stem: `Mock MCAT-style question ${index + 1} for ${input?.topicName ?? "a selected topic"}.`,
      choices: [
        { label: "A", text: "Mock answer choice A", is_correct: true },
        { label: "B", text: "Mock answer choice B" },
        { label: "C", text: "Mock answer choice C" },
        { label: "D", text: "Mock answer choice D" },
      ],
      correct_label: "A",
      brief_rationale: "This mock question is only used to keep local development deterministic.",
      suggested_tags: input?.reasoningSkills ?? [],
    }));
  }

  async classifyQuestion(_input?: ClassifyInput): Promise<Classification> {
    return {
      section: null,
      content_category_id: null,
      topic_id: null,
      subtopic_id: null,
      reasoning_skills: [],
      difficulty: null,
      format: null,
    };
  }

  async diagnoseMistakes(_input?: DiagnoseInput): Promise<DiagnosisReport> {
    return {
      patterns: [],
      summary: "Mock diagnosis summary. Real pattern analysis will be generated by the configured AI provider.",
    };
  }

  async generatePlanNarrative(_input?: PlanInput): Promise<PlanNarrative> {
    return {
      narrative: "Mock study plan narrative. Real study plan wording will be generated by the configured AI provider.",
    };
  }
}
